name: Build and Release uYouPlus

on:
  workflow_dispatch:
    inputs:
      uyou_version:
        description: "The version of the Deb"
        default: "1.1.0"
        required: true
        type: string
      decrypted_youtube_url:
        description: "The direct URL to the decrypted YouTube ipa"
        default: ""
        required: true
        type: string
      bundle_id:
        description: "Modify the bundle ID. Not recommended"
        default: "com.arichorn.lowcontrastmode"
        required: true
        type: string
      create_release:
        description: "Create a draft release"
        default: true
        required: false
        type: boolean

      - name: Setup Theos
        uses: actions/checkout@v3
        with:
          repository: theos/theos
          ref: master
          path: theos
          submodules: recursive
          
      - name: Caching
        id: SDK
        uses: actions/cache@v3.0.11
        env:
          cache-name: LowContrastMode-Deb
        with:
          path: theos/dm.pl/
          key: ${{ env.cache-name }}          
          
      - name: Install Theos Jailed
        run: |
          ./theos-jailed/install
        env:
          THEOS: ${{ github.workspace }}/theos

      - name: Download Deb Entitlements & Build Deb
        run: |
          npm install -g @theosdev/dm.pl
          curl "https://raw.githubusercontent.com/Muirey03/RemoteLog/master/RemoteLog.h" --output "$THEOS/include/RemoteLog.h"
          dpkg-deb -b "youtube/LowContrastMode/com.arichorn.lowcontrastmode_${{ env.LOWCONTRASTMODE_VERSION }}_iphoneos-arm.deb"
